AUTHORS.md

Added myself to the AUTHORS file

---

AUTHORS.md

added name to AUTHORS.md

---

AUTHORS.md

added author

---

AUTHORS.md

part of the optional advanced git lab

added my name to chiventure

---

AUTHORS.md

Adding name to authors

---

AUTHORS.md

Adding author to AUTHORS.md

---

AUTHORS.md

New author

---

AUTHORS.md

I added my name, Lucy Li, to AUTHORS.md.

Added Lucy Li

---

AUTHORS.md

Finally did the lab and added myself to AUTHORS.md

---

AUTHORS.md

Added self to authors

---

AUTHORS.md

Added my name to AUTHORS.md

---

src/action_management/include/actionmanagement.h
src/action_management/src/actionmanagement.c

Just finished the implementation for action_npc, action_item_npc, and action_item_item. Can you take a look and let me know if you'd like me to change anything?

Merging Type 3,4,5 i.e. action_npc, action_item_npc, action_item_item

---

docs/actions.md

This can be automatically merged, but I wanted you to have a look.

Some WDL and default behavior changes to actions.md

---

docs/developer.md

Added section on style guide, and clarified branching strategy

Updates to Developer Guidelines

---

Makefile
src/ui/Makefile

The code merged in #100 does not build correctly. I have updated the top-level Makefile so that this can be caught by CI, and so that future merges are blocked if they do not build correctly. Please use this PR to fix the issues with the UI Makefile.

Fix broken UI build

---

AUTHORS.md

Added my name to the AUTHORS file

Added myself to AUTHORS

---

AUTHORS.md

adding Matthew Yang to authors

ADDING MYSELF TO AUTHORS

---

AUTHORS.md

lol finally made it :) I accidentally branched out of game-state/dev before lol

adding name to game pt 2

---

src/checkpointing/include/save.h
src/checkpointing/src/save.c

I wrote new functions for save_attribute_value, save_attribute, save_condition, and save_path in save.h and save.c. I also updated the old functions to match the new proto file. However, I ignored anything that uses hash tables by leaving a bunch of comments where they would belong.

updated save functions

---

src/checkpointing/include/save.h
src/checkpointing/src/save.c

Hi, I have finished the save game functions and want to merge to dev so others can begin writing their tests. Hopefully, it will be finished quickly so we can all merge to master to integrate with WDL and CLI. Have fun reviewing!

Merging the completed save functions to checkpointing/dev for ultimate deploy to master

---

src/cli/include/operations.h
src/cli/include/validate.h
src/cli/src/cmd.c
src/cli/src/operations.c
src/cli/src/shell.c
src/cli/src/validate.c

Just want someone to do a quick look to make sure the logic here makes sense. Need to have the updated save function from checkpointing to actually test that it works.

Merging save into cli/dev

---

src/cli/src/operations.c

All changes are made in operation.c.

Replaced all item related placeholders with game-state macro

---

src/game-state/include/game.h
src/game-state/include/item.h
src/game-state/include/player.h
src/game-state/include/room.h
src/game-state/src/game.c
src/game-state/src/item.c
src/game-state/src/player.c
src/game-state/src/room.c
src/game-state/tests/test_game.c

Hotfix: Iteration functions for Checkpointing

---

src/checkpointing/tests/Makefile
src/checkpointing/tests/test_load.c

now both tests compile and we can figure out testing for save and load separately

test_load.c compiles

---

docs/GAME-STATE.md
src/game-state/include/game.h
src/game-state/include/game_state_common.h
src/game-state/src/game.c

This pull request to merge a small collaborative feature between WDL and Game State to add an end condition to games. 
As specified by WDL, the end condition will consist of a final_room specified by the developer. move_room() in the game module has been changed to return a specific value when the player moves to the final room. The game struct has been updated to include a final_room field. A function add_final_room_to_game() has been written to add a final room to the game and protect against bad inputs. All relevant documentation has been duly updated. 
Although this is a small feature, I am aiming to get this approved quickly so there is some way to end games before the demo next week.

Adding basic end conditions to game

---

src/action_management/Makefile
src/wdl/Makefile

Issue #354: Included team directories in Makefiles for WDL and AM. Should fix the build fail in Travis.

Updated WDL and action-management Makefiles to fix build fail

---

docs/wdl.md
src/wdl/examples/sample_yaml/connected_rooms.yaml

in docs/wdl.md, the specification was updated to have the following changes:
- The end condition can only be when the player is in a certain room
- The actions must all be in Upper-Case
- The directions must all be in lower-case

Updated WDL spec in wdl.md

---

src/checkpointing/src/save.c

Just getting rid of a fprintf because it messes up the ui for chiventure when saving.

Updated save.c

---

src/cli/src/operations.c

Fixed segfault caused by "go"

---

src/action_management/src/actionmanagement.c

This is a quick bug fix for the actionmanagement.c In our last PR, I introduced a bug in our comparison tests. In this bug fix, I have fixed the bug and everything works again.

HOTFIX: Comparison bug in actionmanagement.c

---

include/wdl/validate.h
src/wdl/sandbox/uthash.c

Addressing Issue #548, I used a variety of uthash functions to search, add, print, and free a hash table. Explored two different hash table structs: one using a string as key, another using a struct as key. This is in preparation for Issue #549, which will need a hash table implementation.

Sandbox using uthash (in preparation for WDL object store)

---

games/test_game.wdl
games/test_game_readme.txt

The test game is loadable and can be won in chiventure, albeit not in an intended way. The failures of the game are listed in the README, and hopefully will be fixed in future iterations- for now, the game serves as a test.

Added new test game

---

src/battle/README.md

Finished src/battles README with a brief overview of all battle src and header files. Our task was to go through the existing battle code and update the wiki page, and after coming across a blank README we decided to fill it in with a high-level overview of each relevant .h and .c file.

Finished battles README #839

---

src/cli/src/operations.c

In relation with issue #357 . 
Goal: Implementing validation of number of objects in command. 
Changes: All changes made in src/operations.c For kind1 and 2 actions, checks to make sure there is not a third token in the array through token[2], which would indicate a presence of an extra object in the command.

Implementing validation of number of objects in command 

---

src/cli/src/operations.c
src/common/src/ctx.c
src/ui/src/print_functions.c

There are a few features implemented by the cli team that were not behaving exactly as intended (because of clashing code merges), so several one-line code fixes have been added to make them compatible. No linked issue.

Fixing some small bugs in CLI
