.travis.yml
This addresses issue #3 
I've added a .travis.yml file and verified it works on the `master` branch of a fork of chiventure (see https://travis-ci.org/borjasotomayor/chiventure/builds/524971592)
I've also activated Travis on uchicago-cs/chiventure, but I suspect there will be additional setup once this pull request is merged.
=> Added Travis CI file

src/action_management/include/actionmanagement.h
There were a number of issues that we decided on during Sprint 3 such as:
- splitting actions into "kinds", or types so that we could better manage them
- placing the synonyms and canonical names within the struct so that they could be accessed by other teams
- creating a "get_supported_actions()" function
I've added these functions to the document and would appreciate any feedback!
=>  Updated action structs to reflect Sprint 3 Discussion (5/10)

Makefile, docs/GAME-STATE.md, src/game-state/Makefile, src/game-state/include/path.h, src/game-state/src/game.c, src/game-state/src/path.c, src/game-state/src/room.c
game-state's build on `master` (from PR #105) is broken and needs to be fixed as soon as possible:
```
chiventure/src/game-state$ make
gcc -fPIC -Wall -Wextra -O2 -g -I./include/ -I../common/include/ -I./src/   -c -o src/game.o src/game.c
src/game.c:2:25: fatal error: common-room.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'src/game.o' failed
make: *** [src/game.o] Error 1
```
=> Hotfix: game-state build on master is broken

src/checkpointing/.gitignore
Created .gitignore to include .pb-c files, as per Mark's request.
=> Create .gitignore for checkpointing .pb-c files

Makefile, src/chiventure.c, src/common/Makefile, src/common/include/ctx.h, src/common/src/ctx.c
Added a context type that can encapsulate all the shared state in chiventure. Currently only includes the game state, but will eventually also include UI and CLI state.
=> Added context type to encapsulate shared state

src/game-state/include/item.h, src/game-state/src/item.c, src/game-state/tests/test_items.c
This PR is to merge the work done by game-state for WDL and AM concerning an "action list" within the item struct. After conversations with both teams, it was realized that the most advantageous way to go about this is providing two function interfaces: add_allowed_action() and allowed_action(), which add an allowed action to an item and check an action's existence respectively. 
On the backend, this works by treating actions the same way we would treat a boolean attribute. 
The functions were written in item.c, interfaced through item.h, and tests written in test-item.c
=> Game state/action list

src/action_management/Makefile
Currently our Makefile compiles into a dynamic library. The project specification says that it must be a static library. The goal of this issue is to make our Makefile in line with the project spec. At the request of CLI we are pushing this directly to master as a hotfix. This is the PR for #198 .
=> Hotfix: Changed makefile to make static library

src/action_management/src/get_actions.c
After talking to CLI we are changing our valid_actions such that all items will be in line with our actions enum. This means we are adding capitalization and replacing spaces with underscores. This issue for this PR is #208.
=> Hotfix: valid_actions to be compatible with CLI

src/game-state/src/game.c, src/game-state/src/item.c, src/game-state/src/path.c, src/game-state/src/player.c, src/game-state/src/room.c
- Memset everything to 0 (NULL) immediately after malloc each struct, so that ui team doesn't get unexpected errors
- Fix errors when init description strings of rooms: malloc and strcpy for the id, long_desc, & short_desc
=> Hotfix: Memset everything immediately after malloc & fix errors for desc strings in room

src/game-state/include/item.h, src/game-state/src/item.c, src/game-state/tests/test_items.c
Added two functions, get_sdesc_item and get_ldesc_item into item.h and item.c. These functions return the short and long descriptions stored in an item (for issue #202). Also added two tests into test_items.c to test these functions.
=> Adding get description from item functions to game-state/dev

src/cli/Makefile, src/cli/include/operations.h, src/cli/src/cmd.c, src/cli/src/operations.c, src/ui/include/ui_ctx.h, src/ui/src/ui.c, src/ui/src/ui_ctx.c
There was a misunderstanding about some code regarding operation types. See issue #268 for a summary. Essentially, I reverted an edit made in #258 that added in a couple dummy parameters to the toggle_map and layout_switch functions, and created some wrapper operations to refactor the code.
=> Organizing functions related to toggle_map and layout_switch

src/action_management/src/actionmanagement.c, src/action_management/tests/test_item_actions.c, src/action_management/tests/test_item_item_actions.c, src/action_management/tests/test_path_actions.c, src/cli/src/operations.c
Changes:
- Merged with actions/dev
- Added a new macro and changed the name of existing NOT_ALLOWED to differentiate between indirect and direct allowed action errors
- Updated actions/dev version of do_item_item_actions to have new return value and also check allowed_actions of indirect and direct items
- Using the added error code groundwork from #289 actions/dev refactored the test_files to take the new return value
This is the PR for #288 #287 #286.
=> Refactored test files to use the new return value from #245

src/cli/examples/testshell.c, src/cli/src/cmd.c, src/cli/src/operations.c
Issue #310. This is meant to give informative error messages when no game has yet been loaded. Essentially, just adding in tests for when there is no game to access, and error messages to occur instead of segfaults.
Files have been tweaked in operations.c in order to insert the messages.
=> Catching errors occuring when game doesn't exist

src/wdl/include/parse.h, src/wdl/src/load_item.c, src/wdl/src/parse.c, src/wdl/tests/test_item.c
This is a pull request to load attributes into the structures provided by the game-state team. In order to complete this, I created a while loop to iterate over the attributes within the attribute list from the document. I also added a function to the parse module to retrieve the attributes associated with a given item. More thorough integration tests will be written once this PR has been approved.
=> PR from wdl/correct-attribute to wdl/dev to load attributes fields and values into game-state structures

src/wdl/examples/sample_yaml/sample.yaml, src/wdl/include/load_room.h, src/wdl/src/load_room.c
This is a pull request to merge the new sample.yaml file into wdl/dev. This is a game that can be parsed by and loaded into game-state structures using the libobj and libwdl functions. It contains the following fields which were not properly streamlined across the previous example files:
- attributes
- associated attribute values
- conditions (id, attribute, value)
- effects (id, attribute, value)
- text_fail
- text_success
The FILE_PATH macro will be modified to reference this file in the wdl_common.h file once this PR has been approved to dev.
This PR also includes streamlining current macro definitions for failure, as game-state requested that these be abstracted away using macros instead of direct integer values.
=> PR from wdl/create_yaml to wdl/dev for sample.yaml example file 

.travis.yml, Makefile, src/action_management/Makefile, src/action_management/tests/Makefile, src/cli/Makefile, src/cli/examples/Makefile, src/cli/tests/Makefile, src/common/Makefile, src/libobj/Makefile, src/ui/Makefile, src/ui/tests/Makefile, src/wdl/Makefile, src/wdl/tests/Makefile
One of the pervasive issues with the Makefiles is that "make clean" actually results in invoking gcc to generate dependency files, instead of just calling "rm". This patch should address that issue.
=> Updated Makefiles to avoid generating .d files when running 'make clean'

src/common/src/sample_game.c
This PR is to correct the add_action calls in the most recent action-management PR #353 (that I approved so this is my bad). Add_action, which is not yet in master, no longer takes in the action_type_t struct.
These changes should allow the #335 game-state PR to build.
=> Correcting inputs in add_action call in sample_game.c

Makefile
As the title indicates, changed the ncurses library in the top Makefile to enable support for Unicode characters used in banner.
=> Changed lncurses to lncursesw in top Makefile

src/game-state/include/game_state_common.h, src/game-state/src/game_action.c
CLI reported a bug of our game-state:
the add_action function causes a segfault in create_sample_game
`strncpy(new_action->action_name, act_name, strlen(act_name));`
this line in game init causes the seg fault
Changes:
In game_action_init(), malloc a size of MAX_MSG_LEN (300) to action->success_str and action->fail_str before strncpy()
=> Fix seg faults in game_action_new()

src/ui/src/print_functions.c
The string I needed was freed for no particular reason. It should still be in use.
=> Emergency fix for name command

src/ui/src/print_functions.c
Fixed issue that when q was pressed the instruction line to press enter or q did not disappear.
=> Fixed issue when q was pressed to quit displaying output

src/cli/src/cmd.c, src/cli/src/operations.c, src/ui/src/print_functions.c
See https://github.com/uchicago-cs/chiventure/pull/374
The changes made roughly follow this form:
In the UI segment: previously, each string put in the input buffer for CLI was malloced but not freed. This was a conscious decision made unilaterally by me and mostly unnoticed by others last year, in order to reuse strings in the buffer as internal references.
(This was an awful idea, made late at night in confusion. I fixed it almost immediately after, but the request was denied due to it being less than 24 hours before final presentations.)
In the CLI segment:
The system adding entries for new commands to the lookup table is the only thing that needs to "remember" raw input, with the deletion of the history command. So I made it copy strings and free the new ones later. 
Lastly, I also …
=> Fixes memory leaks #374

docs/developer.md
Updated the developer guidelines to reflect the new directory structure, and the new branching model we will be using.
I have also added a `dev` branch and made it a protected branch. It looks like GitHub now includes an option to require that a branch be up to date with the branch you're merging with. I've enabled this since it seems like a sensible way of avoiding integration issues, but let me know if there's a reason why we may want to disable this.
This pull request closes #418.
=> Updated developer guidelines

.travis.yml, include/wdl/validate.h, src/wdl/src/load_game.c, src/wdl/src/parse.c, src/wdl/src/validate.c, tests/wdl/test_validation.c
Addressing [Issue#314](https://github.com/uchicago-cs/chiventure/issues/314), the return values in validate.c and validate.h were converted from bool type to the macros SUCCESS and FAILURE.
=> Conform return values in validate files to macros

include/cli/cmd.h, include/ui/print_functions.h, src/cli/examples/testshell.c, src/cli/src/cmd.c, src/ui/src/print_functions.c, tests/cli/CMakeLists.txt, tests/cli/test_game.c
This PR ultimately adds a full-game test to the CLI (where a game is created in-memory from scratch, so we can test CLI functions on it). However, this required some non-trivial re-factoring, because there was no way to test the CLI functions without starting the UI (which prevents the tests from running, since they get stuck in a UI loop). The specific changes are:
- `do_cmd` has been altered to take a callback function (with callback arguments) as parameters. `print_cli` now calls `do_cmd` with a callback function that calls `print_to_cli`.
- The `quit` output parameter of `do_cmd` has been replaced by a return value.
- There was another call to `do_cmd` from `testshell.c` that has also been updated.
With these changes, the full-game test is able to pass a callback function that simply …
=> Added a full-game test to the CLI

src/cli/src/cmd.c, tests/cli/test_game.c
I've added an additional game test for CLI that checks whether the game state has changed as expected, as opposed to checking whether the CLI prints the expected output. This additional test also checks that action management is correctly integrated with the CLI.
Adding this also involved adding support for null callbacks in `do_cmd`.
=> Added additional game test for CLI

include/battle/battle_state.h, src/battle/src/battle_state.c
This pull request fixes two minor errors in battle_state.c. 
1. Changing combatant_free() line 66-68 to iterate over and delete combatant's items instead of moves. 
2. Allocating space for MAX_NAME_LEN + 1 in calloc call in combatant_init(), instead of MAX_NAME_LEN.
=> Battle State Minor Fixes (calloc, combatant_free)

include/common/ctx.h, include/ui/print_functions.h, src/chiventure.c, src/cli/CMakeLists.txt, src/cli/examples/extra-command.c, src/common/src/ctx.c, src/ui/src/coordinate.c, src/ui/src/map.c, src/ui/src/ui.c, tests/cli/test_game.c, tests/game-state/test_stats.c
This pull request refactors out a couple of dependencies in chiventure_ctx_t that have proven to be problematic. Most notably:
- The UI context is no longer initialized in `chiventure_ctx_init` but, rather, inside `start_ui` (we could also move this initialization code to `chiventure.c`, but I'm not sure that's necessary given that the only situation where we need an initialized UI context is if we're going to run the UI). This means that the `ncurses.h` header file is only included in the UI code (where previously it ended up being included indirectly from `ctx.h`, which was causing issues for the graphics team)
- `chiventure_ctx_init` and `chiventure_ctx_new` now take a `game_t` as a parameter instead of a filepath. This provides more flexibility when creating a context object, where a …
=> Removed certain dependencies in chiventure_ctx_t

tests/skilltrees/skilltree_test.c
This small change fixes a few typing warnings when trying to make chiventure that were missed by a previous pull request. There is one check inside of one test that is being commented out as it requires a bit more work to fix, but that will be fixed in issue #691 (which will become a PR later tonight/early in the morning tomorrow) in order to prioritize fixing these warnings as soon as possible.
=> Fixing warnings from most recent merge into dev

src/chiventure.c
When calling `chiventure_ctx_new` (or `chiventure_ctx_init`), the `game_t` parameter has to either be NULL or point to a valid game. In `chiventure.c`, the `game` was not being initialized to `NULL`, so the `ctx` functions were treating the (uninitialized) memory it pointed to as a game, leading to a segfault.
=> Hotfix: Uninitialized game was causing segfault

docs/actions.md, include/action_management/action_structs.h
The following action synonyms were implemented without proper documentation in `docs/actions.md`: 
```
// Synonyms for GO
WALK
// Synonyms for USE
CONSUME, EAT, DRINK
```
This PR updates the documentation to reflect the new synonyms, and fixes other errors in  `actions.md`.  It also changes `action_structs.h` to reflect that all synonyms are now both legal and implemented in chiventure.
=> Update Documentation for Action Synonyms

src/chiventure.c
`chiventure.c` had been modified to unconditionally call `load_objects`, when this function should only be called when a WDL file has been specified. Otherwise, the empty game should be loaded as usual.
=> Hotfix: Do not call load_objects if WDL file has not been specified

include/game-state/item.h, src/game-state/src/item.c, src/playerclass/src/class_item_restriction.c, tests/game-state/test_items.c
(Closes #851)
In the current class item restriction code, it is necessary to create an attribute directly in order to add it to the `class_restrictions` field of an item (a linked list of attributes). However, the code in `item.c` only contains type-specific `set_attr` functions that combine the creation of an attribute and its addition to the `attributes` hash table. Since class item restrictions are handled via a linked-list, not the `attributes` hash table, I divided up the two processes occurring in the `set_attr` functions in order to allow for creation of attributes in modules other than `game-state`.
Summary of Major Changes:
- Five type-specific attribute creation functions have been added to `item.c` 
- Relevant tests were added and documentation was updated
- Minor changes in …
=> Adding type-specific attribute creation functions to streamline Player Class/Attribute integration

include/openworld/autogenerate.h, src/openworld/src/autogenerate.c, tests/openworld/test_autogenerate.c
This Pull Request is for refactoring the level-oriented generation code, which puts the functionality of filtering a speclist with a difficulty level into a separate function so that the filtered speclist can be used for other level-oriented autogeneration functions in addition to multi_room_level_generate. 
This involves updating the autogenerate module. Tests are added to test_autogenerate.c. Updates in the autogenerate module include adding filter_speclist_with_difficulty function and modifying multi_room_level_generate function. 
This PR is related to issue #982.
=> Refactor level-oriented generation code

docs/openworld.md
Created a .md file for the openworld module for the chiventure/docs directory which contains:
- A brief description of the openworld module
- A list of wiki pages that include the system and product documentations of the openworld module
- A list of directories of the openworld module with a short description of each file's functionality
Since a feature wishlist [wiki page](https://github.com/uchicago-cs/chiventure/wiki/Open-World-~-Feature-Wishlist) already existed, we created a new [issue](https://github.com/uchicago-cs/chiventure/issues/1085) to update the wiki page with changes made to the openworld module this year and a list of potential new features to be implemented for next year.
=> Openworld Documentation

src/action_management/examples/spring2021-demo.c
The case desensitize update broke the command for getting an item from a hash, so the search was changed from "A sword" to "a sword". This allows for the get_item_in_hash function to properly find the item.
=> Fixes last minute errors in the Action Management Demo Game
